navbar-links:
    Archive: /archives
    Github: https://xr08255920.github.io/
    About: /about/
    Tags: /tags/

avatar: /avatar.jpg
favicon: /avatar.jpg

header:
    title: "Yejf的篝火"
    motto: Loneliness is not the same as loneliness, loneliness will panic, loneliness is full.
    bigimgs:
        - src: /bigimgs/87369142_p0_master1200.jpg
        - src: /bigimgs/87706186_p0_master1200.jpg
        - src: /bigimgs/88663580_p0_master1200.jpg
        - src: /bigimgs/89209550_p0_master1200.jpg
        - src: /bigimgs/89593224_p0_master1200.jpg
        - src: /bigimgs/91523523_p0_master1200.jpg


rss: /atom.xml
googlefonts:
  - "Lora:400,700,400italic,700italic"
  - "Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"

highlight:
  enable: true
# or use any highlight.js style
  # style_path: "/css/highlight.css"
  # style_path: "//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.3/styles/default.min.css"
  style_path: "/css/styles/kimbie-dark.css"


# 自动解析该配置，可以追加任意多个图标
footer:
  github:
    link: 'https://github.com/xr08255920'
    title: GitHub
    icon: fa-github
    enable: true
  rss:
    link: '/atom.xml'
    title: RSS
    icon: fa-rss
    enable: false
  mail:
    link: 'mailto:xr08255920@gmail.com'
    title: Email me
    icon: fa-envelope
    enable: true

google_analytics:

site_counter:
  show: true

comment:
  # false, disqus, netease or facebook
  enable: false
  # disqus user, netease productKey or facebook appid 
  id: 64d7f0abf9224be3bfdcc6cfb9b83fcf
  # [facebook only] plugin language 
  lang: en_US
  # [facebook only] number of posts per load
  numposts: 10

# IMPORTANT NOTE [Facebook Plugin]:
# If you are using Facebook Social Plugin and it's not working, 
# please go to this URL https://developers.facebook.com/tools/debug/og/object/
# copy the link of your post there and press the button "Fetch new scrape information".
# In that way, you are going to update your post metatags Facebook Open Graph information. 
